name: PHPUnit / PHPCS / Phan
on:
  pull_request:
    branches: '**'

  push:
    branches: [ master, REL1_39 ]

jobs:
  build:
    strategy:
      matrix:
        php_version: ['8.0']
        mw: ['REL1_39']

    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          # We don't run any coverage, so we should set this parameter to none
          # as this will disable xdebug which slows all processes significantly
          coverage: none
          extensions: ast
      - uses: actions/checkout@v4

      - name: Checkout Mediawiki
        uses: actions/checkout@v4
        with:
          repository: wikimedia/mediawiki
          ref: ${{ matrix.mw }}

      - name: Checkout Tilesheets extension
        uses: actions/checkout@v3
        with:
          path: extensions/Tilesheets

      - name: Cache Tilesheets composer dependencies
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-v3-${{ hashFiles('extensions/Tilesheets/composer.lock') }}

      - name: Install Tilesheets composer dependencies
        working-directory: ./extensions/Tilesheets
        run: composer install --prefer-dist --no-progress

      - name: Run PHPCS and minus-x
        working-directory: ./extensions/Tilesheets
        run: composer test

      - name: Start MySQL
        run: sudo systemctl start mysql.service

      - name: Install MediaWiki composer dependencies
        run: composer update --prefer-dist --no-progress

      - name: Install & configure MediaWiki
        run: |
          php maintenance/install.php --dbtype mysql --dbuser root --dbpass root --pass TestPassword testwiki TestAdmin

          echo 'error_reporting( E_ALL | E_STRICT );' >> LocalSettings.php
          echo 'ini_set( "display_errors", 1 );' >> LocalSettings.php
          echo '$wgShowExceptionDetails = true;' >> LocalSettings.php
          echo '$wgShowDBErrorBacktrace = true;' >> LocalSettings.php
          echo '$wgDevelopmentWarnings = true;' >> LocalSettings.php

          echo 'wfLoadExtension( "'Tilesheets'" );' >> LocalSettings.php

      - name: Run schema changes
        run: php maintenance/update.php --quick

      - name: Run PHPUnit tests
        run: php tests/phpunit/phpunit.php extensions/Tilesheets/tests
